package nometry.entity;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Cluster")
public class Cluster extends NometryEntity
{
	public static String STATUS_NEW = "NEW";
	
    String id;
    String accountId;
    String name;
    Long createdTimestamp;
    String status;
    Integer replicationLevel;
    Long updateTimestamp;
    
    @DynamoDBHashKey(attributeName="Id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBRangeKey(attributeName="AccountId")
	public String getAccountId() {
		return accountId;
	}
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}
	@DynamoDBAttribute(attributeName="Name")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@DynamoDBAttribute(attributeName="CreatedTimestamp")
	public Long getCreatedTimestamp() {
		return createdTimestamp;
	}
	public void setCreatedTimestamp(Long createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}
	@DynamoDBAttribute(attributeName="Status")
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	@DynamoDBAttribute(attributeName="ReplicationLevel")
	public Integer getReplicationLevel() {
		return replicationLevel;
	}
	public void setReplicationLevel(Integer replicationLevel) {
		this.replicationLevel = replicationLevel;
	}
	@DynamoDBAttribute(attributeName="UpdateTimestamp")
	public Long getUpdateTimestamp() {
		return updateTimestamp;
	}
	public void setUpdateTimestamp(Long updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}
	@Override
	public String retrieveHashKey() {
		return getId();
	}
	@Override
	public String retrieveRangeKey() {
		return getAccountId();
	}
}
