package nometry.entity;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Node")
public class Node extends NometryEntity
{
	public static final String STATUS_UNRESPONSIVE = "UNRESPONSIVE";
	
    String id;
    String clusterId;
    String dnsName;
    String serverStatus;
    
    @DynamoDBHashKey(attributeName="Id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBRangeKey(attributeName="ClusterId")
	public String getClusterId() {
		return clusterId;
	}
	public void setClusterId(String clusterId) {
		this.clusterId = clusterId;
	}
	@DynamoDBAttribute(attributeName="DNSName")
	public String getDnsName() {
		return dnsName;
	}
	public void setDnsName(String dnsName) {
		this.dnsName = dnsName;
	}
	@DynamoDBAttribute(attributeName="ServerStatus")
	public String getServerStatus() {
		return serverStatus;
	}
	public void setServerStatus(String serverStatus) {
		this.serverStatus = serverStatus;
	}
	
	public String retrieveHashKey()
	{
		return getId();
	}
	
	public String retrieveRangeKey()
	{
		return getClusterId();
	}
    
}
